
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Ensure environment variables are set
if (!import.meta.env.VITE_SUPABASE_URL) {
  throw new Error("Missing environment variable: VITE_SUPABASE_URL");
}
if (!import.meta.env.VITE_SUPABASE_ANON_KEY) {
  throw new Error("Missing environment variable: VITE_SUPABASE_ANON_KEY");
}
if (!import.meta.env.VITE_GEMINI_API_KEY) {
  // Optional: You might want to handle this differently if Gemini is not essential
  console.warn("Missing environment variable: VITE_GEMINI_API_KEY");
}

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;
export const GEMINI_API_KEY = import.meta.env.VITE_GEMINI_API_KEY || ""; // Provide a default or handle missing key

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);
